	procesador u0 (
		.clk_clk                               (<connected-to-clk_clk>),                               //                         clk.clk
		.clk_custom_in_clk                     (<connected-to-clk_custom_in_clk>),                     //               clk_custom_in.clk
		.clk_custom_out_clk                    (<connected-to-clk_custom_out_clk>),                    //              clk_custom_out.clk
		.divisor_clock_export                  (<connected-to-divisor_clock_export>),                  //               divisor_clock.export
		.enable_export                         (<connected-to-enable_export>),                         //                      enable.export
		.fifo0_32_bit_in_valid                 (<connected-to-fifo0_32_bit_in_valid>),                 //             fifo0_32_bit_in.valid
		.fifo0_32_bit_in_data                  (<connected-to-fifo0_32_bit_in_data>),                  //                            .data
		.fifo0_32_bit_in_ready                 (<connected-to-fifo0_32_bit_in_ready>),                 //                            .ready
		.fifo0_64_bit_down_in_valid            (<connected-to-fifo0_64_bit_down_in_valid>),            //        fifo0_64_bit_down_in.valid
		.fifo0_64_bit_down_in_data             (<connected-to-fifo0_64_bit_down_in_data>),             //                            .data
		.fifo0_64_bit_down_in_ready            (<connected-to-fifo0_64_bit_down_in_ready>),            //                            .ready
		.fifo0_64_bit_up_in_valid              (<connected-to-fifo0_64_bit_up_in_valid>),              //          fifo0_64_bit_up_in.valid
		.fifo0_64_bit_up_in_data               (<connected-to-fifo0_64_bit_up_in_data>),               //                            .data
		.fifo0_64_bit_up_in_ready              (<connected-to-fifo0_64_bit_up_in_ready>),              //                            .ready
		.fifo1_32_bit_in_valid                 (<connected-to-fifo1_32_bit_in_valid>),                 //             fifo1_32_bit_in.valid
		.fifo1_32_bit_in_data                  (<connected-to-fifo1_32_bit_in_data>),                  //                            .data
		.fifo1_32_bit_in_ready                 (<connected-to-fifo1_32_bit_in_ready>),                 //                            .ready
		.fifo1_64_bit_down_in_valid            (<connected-to-fifo1_64_bit_down_in_valid>),            //        fifo1_64_bit_down_in.valid
		.fifo1_64_bit_down_in_data             (<connected-to-fifo1_64_bit_down_in_data>),             //                            .data
		.fifo1_64_bit_down_in_ready            (<connected-to-fifo1_64_bit_down_in_ready>),            //                            .ready
		.fifo1_64_bit_up_in_valid              (<connected-to-fifo1_64_bit_up_in_valid>),              //          fifo1_64_bit_up_in.valid
		.fifo1_64_bit_up_in_data               (<connected-to-fifo1_64_bit_up_in_data>),               //                            .data
		.fifo1_64_bit_up_in_ready              (<connected-to-fifo1_64_bit_up_in_ready>),              //                            .ready
		.finalizacion_export                   (<connected-to-finalizacion_export>),                   //                finalizacion.export
		.memory_mem_a                          (<connected-to-memory_mem_a>),                          //                      memory.mem_a
		.memory_mem_ba                         (<connected-to-memory_mem_ba>),                         //                            .mem_ba
		.memory_mem_ck                         (<connected-to-memory_mem_ck>),                         //                            .mem_ck
		.memory_mem_ck_n                       (<connected-to-memory_mem_ck_n>),                       //                            .mem_ck_n
		.memory_mem_cke                        (<connected-to-memory_mem_cke>),                        //                            .mem_cke
		.memory_mem_cs_n                       (<connected-to-memory_mem_cs_n>),                       //                            .mem_cs_n
		.memory_mem_ras_n                      (<connected-to-memory_mem_ras_n>),                      //                            .mem_ras_n
		.memory_mem_cas_n                      (<connected-to-memory_mem_cas_n>),                      //                            .mem_cas_n
		.memory_mem_we_n                       (<connected-to-memory_mem_we_n>),                       //                            .mem_we_n
		.memory_mem_reset_n                    (<connected-to-memory_mem_reset_n>),                    //                            .mem_reset_n
		.memory_mem_dq                         (<connected-to-memory_mem_dq>),                         //                            .mem_dq
		.memory_mem_dqs                        (<connected-to-memory_mem_dqs>),                        //                            .mem_dqs
		.memory_mem_dqs_n                      (<connected-to-memory_mem_dqs_n>),                      //                            .mem_dqs_n
		.memory_mem_odt                        (<connected-to-memory_mem_odt>),                        //                            .mem_odt
		.memory_mem_dm                         (<connected-to-memory_mem_dm>),                         //                            .mem_dm
		.memory_oct_rzqin                      (<connected-to-memory_oct_rzqin>),                      //                            .oct_rzqin
		.parameters_1_user_interface_dataout_0 (<connected-to-parameters_1_user_interface_dataout_0>), // parameters_1_user_interface.dataout_0
		.parameters_1_user_interface_dataout_1 (<connected-to-parameters_1_user_interface_dataout_1>), //                            .dataout_1
		.parameters_1_user_interface_dataout_2 (<connected-to-parameters_1_user_interface_dataout_2>), //                            .dataout_2
		.parameters_1_user_interface_dataout_3 (<connected-to-parameters_1_user_interface_dataout_3>), //                            .dataout_3
		.parameters_1_user_interface_dataout_4 (<connected-to-parameters_1_user_interface_dataout_4>), //                            .dataout_4
		.parameters_1_user_interface_dataout_5 (<connected-to-parameters_1_user_interface_dataout_5>), //                            .dataout_5
		.parameters_1_user_interface_dataout_6 (<connected-to-parameters_1_user_interface_dataout_6>), //                            .dataout_6
		.parameters_1_user_interface_dataout_7 (<connected-to-parameters_1_user_interface_dataout_7>), //                            .dataout_7
		.parameters_1_user_interface_dataout_8 (<connected-to-parameters_1_user_interface_dataout_8>), //                            .dataout_8
		.parameters_1_user_interface_dataout_9 (<connected-to-parameters_1_user_interface_dataout_9>), //                            .dataout_9
		.parameters_1_user_interface_datain_10 (<connected-to-parameters_1_user_interface_datain_10>), //                            .datain_10
		.parameters_1_user_interface_datain_11 (<connected-to-parameters_1_user_interface_datain_11>), //                            .datain_11
		.parameters_1_user_interface_datain_12 (<connected-to-parameters_1_user_interface_datain_12>), //                            .datain_12
		.parameters_1_user_interface_datain_13 (<connected-to-parameters_1_user_interface_datain_13>), //                            .datain_13
		.parameters_1_user_interface_datain_14 (<connected-to-parameters_1_user_interface_datain_14>), //                            .datain_14
		.parameters_1_user_interface_datain_15 (<connected-to-parameters_1_user_interface_datain_15>), //                            .datain_15
		.parameters_2_user_interface_dataout_0 (<connected-to-parameters_2_user_interface_dataout_0>), // parameters_2_user_interface.dataout_0
		.parameters_2_user_interface_dataout_1 (<connected-to-parameters_2_user_interface_dataout_1>), //                            .dataout_1
		.parameters_2_user_interface_dataout_2 (<connected-to-parameters_2_user_interface_dataout_2>), //                            .dataout_2
		.parameters_2_user_interface_dataout_3 (<connected-to-parameters_2_user_interface_dataout_3>), //                            .dataout_3
		.parameters_2_user_interface_dataout_4 (<connected-to-parameters_2_user_interface_dataout_4>), //                            .dataout_4
		.parameters_2_user_interface_dataout_5 (<connected-to-parameters_2_user_interface_dataout_5>), //                            .dataout_5
		.parameters_2_user_interface_dataout_6 (<connected-to-parameters_2_user_interface_dataout_6>), //                            .dataout_6
		.parameters_2_user_interface_dataout_7 (<connected-to-parameters_2_user_interface_dataout_7>), //                            .dataout_7
		.parameters_2_user_interface_dataout_8 (<connected-to-parameters_2_user_interface_dataout_8>), //                            .dataout_8
		.parameters_2_user_interface_dataout_9 (<connected-to-parameters_2_user_interface_dataout_9>), //                            .dataout_9
		.parameters_2_user_interface_datain_10 (<connected-to-parameters_2_user_interface_datain_10>), //                            .datain_10
		.parameters_2_user_interface_datain_11 (<connected-to-parameters_2_user_interface_datain_11>), //                            .datain_11
		.parameters_2_user_interface_datain_12 (<connected-to-parameters_2_user_interface_datain_12>), //                            .datain_12
		.parameters_2_user_interface_datain_13 (<connected-to-parameters_2_user_interface_datain_13>), //                            .datain_13
		.parameters_2_user_interface_datain_14 (<connected-to-parameters_2_user_interface_datain_14>), //                            .datain_14
		.parameters_2_user_interface_datain_15 (<connected-to-parameters_2_user_interface_datain_15>), //                            .datain_15
		.parameters_3_user_interface_dataout_0 (<connected-to-parameters_3_user_interface_dataout_0>), // parameters_3_user_interface.dataout_0
		.parameters_3_user_interface_dataout_1 (<connected-to-parameters_3_user_interface_dataout_1>), //                            .dataout_1
		.parameters_3_user_interface_dataout_2 (<connected-to-parameters_3_user_interface_dataout_2>), //                            .dataout_2
		.parameters_3_user_interface_dataout_3 (<connected-to-parameters_3_user_interface_dataout_3>), //                            .dataout_3
		.parameters_3_user_interface_dataout_4 (<connected-to-parameters_3_user_interface_dataout_4>), //                            .dataout_4
		.parameters_3_user_interface_dataout_5 (<connected-to-parameters_3_user_interface_dataout_5>), //                            .dataout_5
		.parameters_3_user_interface_dataout_6 (<connected-to-parameters_3_user_interface_dataout_6>), //                            .dataout_6
		.parameters_3_user_interface_dataout_7 (<connected-to-parameters_3_user_interface_dataout_7>), //                            .dataout_7
		.parameters_3_user_interface_dataout_8 (<connected-to-parameters_3_user_interface_dataout_8>), //                            .dataout_8
		.parameters_3_user_interface_dataout_9 (<connected-to-parameters_3_user_interface_dataout_9>), //                            .dataout_9
		.parameters_3_user_interface_datain_10 (<connected-to-parameters_3_user_interface_datain_10>), //                            .datain_10
		.parameters_3_user_interface_datain_11 (<connected-to-parameters_3_user_interface_datain_11>), //                            .datain_11
		.parameters_3_user_interface_datain_12 (<connected-to-parameters_3_user_interface_datain_12>), //                            .datain_12
		.parameters_3_user_interface_datain_13 (<connected-to-parameters_3_user_interface_datain_13>), //                            .datain_13
		.parameters_3_user_interface_datain_14 (<connected-to-parameters_3_user_interface_datain_14>), //                            .datain_14
		.parameters_3_user_interface_datain_15 (<connected-to-parameters_3_user_interface_datain_15>), //                            .datain_15
		.parameters_user_interface_dataout_0   (<connected-to-parameters_user_interface_dataout_0>),   //   parameters_user_interface.dataout_0
		.parameters_user_interface_dataout_1   (<connected-to-parameters_user_interface_dataout_1>),   //                            .dataout_1
		.parameters_user_interface_dataout_2   (<connected-to-parameters_user_interface_dataout_2>),   //                            .dataout_2
		.parameters_user_interface_dataout_3   (<connected-to-parameters_user_interface_dataout_3>),   //                            .dataout_3
		.parameters_user_interface_dataout_4   (<connected-to-parameters_user_interface_dataout_4>),   //                            .dataout_4
		.parameters_user_interface_dataout_5   (<connected-to-parameters_user_interface_dataout_5>),   //                            .dataout_5
		.parameters_user_interface_dataout_6   (<connected-to-parameters_user_interface_dataout_6>),   //                            .dataout_6
		.parameters_user_interface_dataout_7   (<connected-to-parameters_user_interface_dataout_7>),   //                            .dataout_7
		.parameters_user_interface_dataout_8   (<connected-to-parameters_user_interface_dataout_8>),   //                            .dataout_8
		.parameters_user_interface_dataout_9   (<connected-to-parameters_user_interface_dataout_9>),   //                            .dataout_9
		.parameters_user_interface_datain_10   (<connected-to-parameters_user_interface_datain_10>),   //                            .datain_10
		.parameters_user_interface_datain_11   (<connected-to-parameters_user_interface_datain_11>),   //                            .datain_11
		.parameters_user_interface_datain_12   (<connected-to-parameters_user_interface_datain_12>),   //                            .datain_12
		.parameters_user_interface_datain_13   (<connected-to-parameters_user_interface_datain_13>),   //                            .datain_13
		.parameters_user_interface_datain_14   (<connected-to-parameters_user_interface_datain_14>),   //                            .datain_14
		.parameters_user_interface_datain_15   (<connected-to-parameters_user_interface_datain_15>),   //                            .datain_15
		.reset_reset_n                         (<connected-to-reset_reset_n>),                         //                       reset.reset_n
		.reset_fifos_reset                     (<connected-to-reset_fifos_reset>),                     //                 reset_fifos.reset
		.reset_op_export                       (<connected-to-reset_op_export>),                       //                    reset_op.export
		.result0_32_bit_in_export              (<connected-to-result0_32_bit_in_export>),              //           result0_32_bit_in.export
		.result0_64_bit_down_in_export         (<connected-to-result0_64_bit_down_in_export>),         //      result0_64_bit_down_in.export
		.result0_64_bit_up_in_export           (<connected-to-result0_64_bit_up_in_export>),           //        result0_64_bit_up_in.export
		.result1_32_bit_in_export              (<connected-to-result1_32_bit_in_export>),              //           result1_32_bit_in.export
		.result1_64_bit_down_in_export         (<connected-to-result1_64_bit_down_in_export>),         //      result1_64_bit_down_in.export
		.result1_64_bit_up_in_export           (<connected-to-result1_64_bit_up_in_export>)            //        result1_64_bit_up_in.export
	);

